#!/bin/bash

psql -d $DB_NAME -U $DB_USER -h $DB_HOST -p $DB_PORT -c "CREATE TABLE IF NOT EXISTS $DB_TABLE (
    collection_id SERIAL PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid (),
    name VARCHAR NOT NULL,
    description TEXT,
    code VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT COLLECTION_UUID_UNIQUE UNIQUE (uuid)
);"