name: Project setup

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v5
        with: 
          postgresql-version: 14
          port: 5432
          database: evershop
          username: postgres
          password: root

      - name: Install dependencies
        run: npm install

      - name: Setup database schema
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: evershop
          DB_USER: postgres
          DB_TABLE: admin_user
          ADMIN_EMAIL: admin@admin.com
          ADMIN_PASSWORD: admin1234
          SUPPRESS_NO_CONFIG_WARNING: "true"
          PGPASSWORD: root
        run:  |
          psql -d $DB_NAME -U $DB_USER -h $DB_HOST -p $DB_PORT -c "CREATE TABLE IF NOT EXISTS $DB_TABLE ("admin_user_id" INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,"uuid" UUID NOT NULL DEFAULT gen_random_uuid (),"status" boolean NOT NULL DEFAULT TRUE,"email" varchar NOT NULL,"password" varchar NOT NULL,"full_name" varchar DEFAULT NULL,"created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ADMIN_USER_EMAIL_UNIQUE" UNIQUE ("email"),CONSTRAINT "ADMIN_USER_UUID_UNIQUE" UNIQUE ("uuid"));"
          npm run user:create -- --name admin --email $ADMIN_EMAIL --password $ADMIN_PASSWORD 
          npm run dev &

      - name: Wait for development server
        run: |
          sudo apt-get install wait-for-it -y
          wait-for-it -h localhost -p 3000 -t 10

      - name: Run e2e tests
        working-directory: tests
        run: |
          npm install
          npx playwright install chromium
          npm run test:e2e e2e